spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/storenew?createDatabaseIfNotExist=true
    username: root
    password: NewPassword123!
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
Strip:
  apiUrl: http://localhost:3000
  timeout: 1000
  enabled: true
  currencies: USD,EUR,GBP
payment-gateway: stripe
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG